# Generated by Django 6.0 on 2025-12-27 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='plan_type',
            field=models.CharField(choices=[('free', 'Free Trial'), ('starter', 'Starter Shop'), ('growth', 'Growth Brand'), ('agency', 'Agency Elite')], default='free', max_length=20),
        ),
    ]
